-- Compress with extended storage postgres toast

-- PART
-- ALTER TABLE PART ALTER P_PARTKEY SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_NAME SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_MFGR SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_BRAND SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_TYPE SET STORAGE EXTENDED;
-- ALTER TABLE PART ALTER P_SIZE SET STORAGE MAIN;
ALTER TABLE PART ALTER P_CONTAINER SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_RETAILPRICE SET STORAGE EXTENDED;
ALTER TABLE PART ALTER P_COMMENT SET STORAGE EXTENDED;

-- SUPPLIER
-- ALTER TABLE SUPPLIER ALTER S_SUPPKEY SET STORAGE EXTENDED;
ALTER TABLE SUPPLIER ALTER S_NAME SET STORAGE EXTENDED;
ALTER TABLE SUPPLIER ALTER S_ADDRESS SET STORAGE EXTENDED;
-- ALTER TABLE SUPPLIER ALTER S_NATIONKEY SET STORAGE EXTENDED;
ALTER TABLE SUPPLIER ALTER S_PHONE SET STORAGE EXTENDED;
ALTER TABLE SUPPLIER ALTER S_ACCTBAL SET STORAGE EXTENDED;
ALTER TABLE SUPPLIER ALTER S_COMMENT SET STORAGE EXTENDED;

-- PARTSUPP
-- ALTER TABLE PARTSUPP ALTER PS_PARTKEY SET STORAGE EXTENDED;
-- ALTER TABLE PARTSUPP ALTER PS_SUPPKEY SET STORAGE EXTENDED;
-- ALTER TABLE PARTSUPP ALTER PS_AVAILQTY SET STORAGE EXTENDED;
ALTER TABLE PARTSUPP ALTER PS_SUPPLYCOST SET STORAGE EXTENDED;
ALTER TABLE PARTSUPP ALTER PS_COMMENT SET STORAGE EXTENDED;

-- CUSTOMER
-- ALTER TABLE CUSTOMER ALTER C_CUSTKEY SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_NAME SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_ADDRESS SET STORAGE EXTENDED;
-- ALTER TABLE CUSTOMER ALTER C_NATIONKEY SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_PHONE SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_ACCTBAL SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_MKTSEGMENT SET STORAGE EXTENDED;
ALTER TABLE CUSTOMER ALTER C_COMMENT SET STORAGE EXTENDED;

-- ORDERS
-- ALTER TABLE ORDERS ALTER O_ORDERKEY SET STORAGE EXTENDED;
-- ALTER TABLE ORDERS ALTER O_CUSTKEY SET STORAGE EXTENDED;
ALTER TABLE ORDERS ALTER O_ORDERSTATUS SET STORAGE EXTENDED;
ALTER TABLE ORDERS ALTER O_TOTALPRICE SET STORAGE EXTENDED;
-- ALTER TABLE ORDERS ALTER O_ORDERDATE SET STORAGE EXTENDED;
ALTER TABLE ORDERS ALTER O_ORDERPRIORITY SET STORAGE EXTENDED;
ALTER TABLE ORDERS ALTER O_CLERK SET STORAGE EXTENDED;
-- ALTER TABLE ORDERS ALTER O_SHIPPRIORITY SET STORAGE EXTENDED;
ALTER TABLE ORDERS ALTER O_COMMENT SET STORAGE EXTENDED;

-- LINEITEM
-- ALTER TABLE LINEITEM ALTER L_ORDERKEY SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_PARTKEY SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_SUPPKEY SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_LINENUMBER SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_QUANTITY SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_EXTENDEDPRICE SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_DISCOUNT SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_TAX SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_RETURNFLAG SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_LINESTATUS SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_SHIPDATE SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_COMMITDATE SET STORAGE EXTENDED;
-- ALTER TABLE LINEITEM ALTER L_RECEIPTDATE SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_SHIPINSTRUCT SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_SHIPMODE SET STORAGE EXTENDED;
ALTER TABLE LINEITEM ALTER L_COMMENT SET STORAGE EXTENDED;

-- NATION
-- ALTER TABLE NATION ALTER N_NATIONKEY SET STORAGE EXTENDED;
ALTER TABLE NATION ALTER N_NAME SET STORAGE EXTENDED;
-- ALTER TABLE NATION ALTER N_REGIONKEY SET STORAGE EXTENDED;
ALTER TABLE NATION ALTER N_COMMENT SET STORAGE EXTENDED;

-- REGION
-- ALTER TABLE REGION ALTER R_REGIONKEY SET STORAGE EXTENDED;
ALTER TABLE REGION ALTER R_NAME SET STORAGE EXTENDED;
ALTER TABLE REGION ALTER R_COMMENT SET STORAGE EXTENDED;

-- Extension compression create
CREATE EXTENSION IF NOT EXISTS pg_prewarm;
CREATE EXTENSION IF NOT EXISTS pg_squeeze;

-- Add tables to pg_squeeze
INSERT INTO squeeze.tables (tabschema, tabname, schedule)
VALUES 
    ('public', 'part', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'supplier', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'partsupp', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'customer', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'orders', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'lineitem', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'nation', ('{30}', '{22}', NULL, NULL, '{3, 5}')),
    ('public', 'region', ('{30}', '{22}', NULL, NULL, '{3, 5}'))
ON CONFLICT DO NOTHING;

SELECT squeeze.start_worker();
