-- PART
ALTER TABLE PART ALTER P_PARTKEY SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_NAME SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_MFGR SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_BRAND SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_TYPE SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_SIZE SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_CONTAINER SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_RETAILPRICE SET STORAGE PLAIN;
ALTER TABLE PART ALTER P_COMMENT SET STORAGE PLAIN;

-- SUPPLIER
ALTER TABLE SUPPLIER ALTER S_SUPPKEY SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_NAME SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_ADDRESS SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_NATIONKEY SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_PHONE SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_ACCTBAL SET STORAGE PLAIN;
ALTER TABLE SUPPLIER ALTER S_COMMENT SET STORAGE PLAIN;

-- PARTSUPP
ALTER TABLE PARTSUPP ALTER PS_PARTKEY SET STORAGE PLAIN;
ALTER TABLE PARTSUPP ALTER PS_SUPPKEY SET STORAGE PLAIN;
ALTER TABLE PARTSUPP ALTER PS_AVAILQTY SET STORAGE PLAIN;
ALTER TABLE PARTSUPP ALTER PS_SUPPLYCOST SET STORAGE PLAIN;
ALTER TABLE PARTSUPP ALTER PS_COMMENT SET STORAGE PLAIN;

-- CUSTOMER
ALTER TABLE CUSTOMER ALTER C_CUSTKEY SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_NAME SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_ADDRESS SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_NATIONKEY SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_PHONE SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_ACCTBAL SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_MKTSEGMENT SET STORAGE PLAIN;
ALTER TABLE CUSTOMER ALTER C_COMMENT SET STORAGE PLAIN;

-- ORDERS
ALTER TABLE ORDERS ALTER O_ORDERKEY SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_CUSTKEY SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_ORDERSTATUS SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_TOTALPRICE SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_ORDERDATE SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_ORDERPRIORITY SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_CLERK SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_SHIPPRIORITY SET STORAGE PLAIN;
ALTER TABLE ORDERS ALTER O_COMMENT SET STORAGE PLAIN;

-- LINEITEM
ALTER TABLE LINEITEM ALTER L_ORDERKEY SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_PARTKEY SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_SUPPKEY SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_LINENUMBER SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_QUANTITY SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_EXTENDEDPRICE SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_DISCOUNT SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_TAX SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_RETURNFLAG SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_LINESTATUS SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_SHIPDATE SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_COMMITDATE SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_RECEIPTDATE SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_SHIPINSTRUCT SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_SHIPMODE SET STORAGE PLAIN;
ALTER TABLE LINEITEM ALTER L_COMMENT SET STORAGE PLAIN;

-- NATION
ALTER TABLE NATION ALTER N_NATIONKEY SET STORAGE PLAIN;
ALTER TABLE NATION ALTER N_NAME SET STORAGE PLAIN;
ALTER TABLE NATION ALTER N_REGIONKEY SET STORAGE PLAIN;
ALTER TABLE NATION ALTER N_COMMENT SET STORAGE PLAIN;

-- REGION
ALTER TABLE REGION ALTER R_REGIONKEY SET STORAGE PLAIN;
ALTER TABLE REGION ALTER R_NAME SET STORAGE PLAIN;
ALTER TABLE REGION ALTER R_COMMENT SET STORAGE PLAIN;

-- Drop extensions
DROP EXTENSION IF EXISTS pg_prewarm;
DROP EXTENSION IF EXISTS pg_squeeze;
